### ISSUE TITLE
DRMAA seems to be un-activated on cluster

### ISSUE THREAD

**Issue by rchailan** [MirmidonDev/mirmidon_unstable#10]

**Comment by rchailan** [comment]
Le push 03aeb23 est sensé corriger le bug. Cela venait de la configuration Local qui avait était poussée par mégarde sur le cluster. 

@cyril-r Peux-tu tester un redémarrage de l'API pour voir si le bug est fixé ?

**Comment by cyril-r** [comment]
API redémarrée, pas de message d'erreur.
Il faudrait un redéploiement du noeud pour être sur.

**Comment by rchailan** [comment]
Je clos l'issue et on verra au prochain redéploiement si erreur il y a ou non. Mais normalement c'est ok. Merci !
