### ISSUE TITLE
/login : Header Set-Cookie introuvable

### ISSUE THREAD

**Issue by cyril-r** [MirmidonDev/mirmidon_unstable#11]
Lors de la connexion d'un user, le header Set-Cookie à disparu, il n'est plus possible pour GUI de sauvegarder le cookie de connexion envoyé par l'API.

Chose troublante, cela semble fonctionner via postman.
Dump de la requête et de la réponse API, on voit qu'il manque bien ce header (en bas) et la requête semble correctement formée.

12/12/2014 10:55:56 POST @ http://xxxxx:9082/login
Request Headers
array (size=2)
  'Accept' => string 'application/json' (length=16)
  'Content-type' => string 'application/json' (length=16)
Request Body
string '{"username":"cyril","password":"nope","fieldsite_id":0}' (length=58)
Response
object(HttpResponse)[21]
  private 'code' => int 200
  private 'raw_body' => string '{"user_id":21,"username":"cyril","email":"nope@gmail.com","name":"Cyril","last_access":"Fri Dec 12 10:56:39 CET 2014","token":"nope","roles":{}}' (length=185)
  private 'body' => 
    array (size=7)
      'user_id' => int 21
      'username' => string 'cyril' (length=5)
      'email' => string 'nope@gmail.com' (length=23)
      'name' => string 'Cyril' (length=5)
      'last_access' => string 'Fri Dec 12 10:56:39 CET 2014' (length=28)
      'token' => string 'nope' (length=36)
      'roles' => 
        array (size=0)
          empty
  private 'headers' => 
    array (size=1)
      'Content-Type' => string 'application/json; charset=utf-8' (length=31)

**Comment by cyril-r** [comment]
Après investigations, si je me log et que je récupère via postman le cookie complet : 

'Cookie' => string 'PLAY_SESSION="5a6186df16d1e2bbd3d54aa6fca24aeb1723bed4-MIRMIDON-AUTH-TOKEN=88f35667-af2e-44ce-af49-7205a19dad9a"' (length=112)

Et que je le reproduit via php, ça fonctionne.

Le problème est que lors du login, il n'y à plus d'entête "Set-Cookie" que je peux copier via le client WEB, vu que tu me renvoie le token dans le json lors du login, je peux forger un cookie qui le contient, mais je me suis rendu compte qu'il fallait le token ET la valeur de PLAY_SESSION, sinon la page de test ne s'affiche pas.

Au final il faut clarifier qu'est-ce que l'API renvoie lors de la phase de login et surtout qu'est-ce que le client doit renvoyer (soit dans ses headers, soit via cookie).

**Comment by rchailan** [comment]
On peut passer MIRMIDON-AUTH-TOKEN=letoken en header si tu veux ? Je ne comprends tjrs pas trop pourquoi la session ca ne marche pas. Je trouvais ca un peu plus élégant car masqué des appels REST. À savoir qu'il va falloir également passer le FIELDSITE=fieldsite... On peut partir sur 
0- l'API sauve dans cookie ET renvoie l'info token (/login) et fielsite (/fieldsite)
1- l'API lis les headers MIRMIDON-AUTH-TOKEN et FIELDSITE de la request pour faire les vérifs authentifications. 

Je ne vois pas où je peux avoir le controle sur la valeur de PLAY_SESSION c'est pour ca...

Me dire s'il faut faire ca.. Car je dois réfractoré à pas mal d'endroit

**Comment by cyril-r** [comment]
Pour moi ça ne change rien, que le token soit transmis à l'API via cookie ou via header c'est pareil.

Au niveau de la récupération du token par le client, que ce soit via les header (et Set-Cookie comme avant) ou bien dans le json renvoyé par l'api, c'est pareil à coder.

Il faut simplement que quel que soit le cas, le protocole de communication du token ou de tout autre élément persistent d'identification soit clair et bien respecté, tant par l'API que par le client et que ce soit documenté.

**Comment by rchailan** [comment]
Ok on passe MIRMIDON-AUTH-TOKEN en header de chaque requete depuis le client vers l'API.
Ce token est récupéré au moment du /login dans le json de retour. 

On fera de même pour FIELDSITE

**Comment by cyril-r** [comment]
Vu, documentation à updater donc.
Je m'occupe d'updater mlogic_connect et la partie authentication de la GUI.

**Comment by rchailan** [comment]
OK. La doc sera a reprendre de toute façon. Je vais faire une issue pour ca. Je vais assigner @jhuon :)

**Comment by cyril-r** [comment]
Tu va avoir du mal il ne bosse plus littoral jusqu'au 21 si je ne me trompe pas :-)

**Comment by rchailan** [comment]
Le process d'authentification a été corrigé. Désormais le /login renvoie le token qui doit être conservé côté client (il reste accessible dans la session/cookie PLAY mais difficilement accessible depuis PHP apparemment).
Pour des actions qui requiert une authentification, il faut bien placer MIRMIDON-AUTH-TOKEN=letoken pour ne pas se faire éjecter par l'API.
Il en va de même avec la notion de FIELDSITE dont l'id du fieldsite choisi doit être conservé par le client. Il est retourné lorsqu'on accède au /fieldsite/<idfieldsite>. Peut-etre faut il encodé l'id du fieldsite ?
C'est une autre question je marque celle ci comme résolue.
