### ISSUE TITLE
Install GMT 5.x on cluster

### ISSUE THREAD

**Issue by rchailan** [MirmidonDev/mirmidon_unstable#12]
Voir avec Fab pour plus de détail vis à vis d'un script d'install pour GMT.

**Comment by cyril-r** [comment]
C'est scripté, à tester lors du prochain redéploiement du noeud ... début 2015 :)

**Comment by cyril-r** [comment]
L'issue n'est pas résolue, je garde mon ticket pour le fermer après les vacances si tout se passe bien lors de la réinstall.

**Comment by cyril-r** [comment]
done.

[mirmidon@Mirmidon-node-0-0 ~]$ gmt --version
5.1.1
