### ISSUE TITLE
websocket integration for mnotification

### ISSUE THREAD

**Issue by rchailan** [MirmidonDev/mirmidon_unstable#15]
À voir avec moi

**Comment by rchailan** [comment]
Notifications avec websocket monochannel.

**Comment by cyril-r** [comment]
Un petit problème lors de l'intégration de la feature:

Lorsque l'on se connecte sur le websocket, on obtiens un string qui dit "Welcome to Mirmidon Websocket connection!"

Ca pose problème car je m'attendrais plutôt a avoir un json avec la liste des notifications existantes pour mon user.

D'ailleurs toutes les communications via websocket devraient être du json.

C'est possible?

**Comment by rchailan** [comment]
ok je vais te faire ca

**Comment by rchailan** [comment]
you may give it a try. Par contre je n'ai pas pu envoyer du JSON à travers le websocket. Je crois que c'est une restriction car on dirait que c'est possible avec play 2.3.X. Je convertis donc au dernier moment le json en String. Dis moi si ca marche (et que ca te va).

**Comment by cyril-r** [comment]
Ca devrait le faire, je fais déjà un JSON.parse du côté client, c'est juste que le welcome-msg n'était pas du json.

Je suis plus a la fac donc réponse demain.

**Comment by cyril-r** [comment]
C'est bizarre je ne parviens plus a me connecter au websocket, tu peux vérifier? (la connexion boucle de mon côté et je ne récupère aucune donnée).

**Comment by rchailan** [comment]
En fait... y a un probleme. Je ne peux pas te remonter les notifs de l'utilisateur courant simplement. Car je n'ai pas de context HTTP lors de la connection websocket. Avec cette version de play l'integration socket / client ca semble...compliqué. Il faudrait upgrader play! pour changer la facon de gerer les websockets (notamment avec systeme d'actor). Mais pour la V1 je pense que ce n'est pas la peine. Non en fait je vais dire meme plus directement : on ne va pas le faire. 
DONC, je te propose de t'envoyer TOUTES les notifs (tout user confondu), ou simplement celles qui ne sont pas lues, ou je ne sais pas un autre critère qui t'intéresse ... Je fix en mettant toutes les notifs pour le moment...

**Comment by rchailan** [comment]
Pushed

**Comment by cyril-r** [comment]
Bon ok, c'est crade mais pour la démo on fera avec.

Ya moyen que tu m'envoie un UID dans chaque notif? (ou que tu me groupe les notifs par UID), avec ça je pourrais côté client filtrer pour faire apparaitre uniquement celles de l'user courant.

Bien sur à réfactorer au plus vite.

**Comment by cyril-r** [comment]
Suite à discussion de ce midi, 
Proposition:

Je me connecte en websockets, tu m'envoie un json de la forme:

``` json
{
  "msg_type":"service",
  "status":0,
  "message":"Welcome to Mirmidon Websocket connection, waiting for credentials."
}
```

`msg_type` : service signifie que c'est un message de service qui est envoyé
`status` : 0 = connexion ok et acceptée, tout autre code = refusé/échec/maintenance api (à affiner si besoin).
`message` : juste un hint.

Une fois que le client à reçu ça, il t'envoie le json suivant:

``` json
{
    "token":"MY_TOKEN"
}
```

Suite à cet envoi, l'API doit valider le token, s'il est accepté on doit récupérer la liste de toutes les notifications pour notre utilisateur pour l'affichage initial, et le client écoutera le canal pour les futures notifications (individuelles).

Si le token est refusé (ou les données reçues invalides) l'API ferme immédiatement la connexion avec le code 1008 (je vois pas de meilleur code dans la RFC websockets http://tools.ietf.org/html/rfc6455#section-7.4 ).

**Comment by rchailan** [comment]
Quand je ferme la connexion je ne peux pas envoyer de code http. Par contre je t'envoie le json(string) 

``` json
{"msg_type":"service","status":401,"message":"Unauthorized"}
```

si le token saisi ne correspond pas à un vrai user.

**Comment by cyril-r** [comment]
Réouverture du ticket: 

Lors de la connexion au websocket j'obtiens bien le JSON initial qui demande le token, mais lorsque j'envoie à l'API mon token (ou tout autre chose pour faire fermer la connexion), rien ne se passe.

Voici ce que j'envoie une fois avoir reçu le message d'accueil (exemple):

``` json
{ 
"token": "xyz-xyz-xyz-xyz-xyz"
 }
```

J'ai pensé à un problème de client JS mais j'écarte cette piste puisque le résultat avec un client websocket chrome donne le même résultat, lorsque j'envoie quelque chose, que ce soit valide ou pas, il ne se passe rien je n'ai aucun retour.

Edit : Après un reload api çà fonctionne, probablement une mauvaise manip qui à bloqué le canal de mon côté.
