### ISSUE TITLE
/configuration/model/list dysfonctionnel + réfactoring

### ISSUE THREAD

**Issue by cyril-r** [MirmidonDev/mirmidon_unstable#16]
GET **http://...:9082/configuration/model/list?idFieldSite=1** ne fonctionne pas.

De plus l'appel devrait être sous la forme suivante: 

GET **http://...:9082/configuration/model/list/<id_fieldsite>** si l'id du fieldsite peut être librement changé OU **http://...:9082/configuration/model/list/** si on utilise uniquement le fieldsite courant (connu par l'API et donc inutile de le préciser).

Ci-dessous l'erreur rencontrée lors de l'accès à la méthode:

```
Execution exception
[NullPointerException: null]
In /data/MIRMIDON/unstable/mirmidon/LOGIC/app/controllers/m_configuration_builder/ConfigurationManager.java at line 103.
100
101        data.put("models", configurations);
102
103        final ObjectNode result = MJsonResultFactory.getResultJson(Constant.resultCode.get("OK"), data);
104        return ok(result);
105    }
106    
107
108    /**
```

**Comment by rchailan** [comment]
Je sais. C'est normal car c'est Fabien qui doit se charger de ceci. Il est au courant. Forcément c'est bloquant désormais...

**Comment by rchailan** [comment]
a été réfractoré
