### ISSUE TITLE
Nom de fieldsite unique

### ISSUE THREAD

**Issue by jhuon** [MirmidonDev/mirmidon_unstable#25]
L'API renvoie une erreur lorsqu'on essaye de créer un fieldsite avec un nom déjà existant.
Hors il est possible qu'une même utilisateur ou que différents utilisateurs appellent un fieldsite du même nom. Pourquoi limiter les noms de fieldsite que les utilisateurs peuvent entrer ?

**Comment by rchailan** [comment]
parce qu'on est en V1

**Comment by cyril-r** [comment]
Vu, pour la V2 donc.

**Comment by rchailan** [comment]
non en fait je l'ai corrigé. Ca venait d'un probleme de là V0.5.
