### ISSUE TITLE
Drmaa refractor

### ISSUE THREAD

**Issue by rchailan** [MirmidonDev/mirmidon_unstable#26]
Refractor drmaa pour que ca marche !!!!

**Comment by rchailan** [comment]
@cyril-r : peux-tu faire un nouveau "run" de l'API (+ database populator ).
Attention je ne sais pas si tu peux directement tenter le mode de production étant donné que la DB doit se mettre à jour. Je pense qu'il faut faire d'abord un run, mettre à jour la db (en tapant direct sur mirmidon) puis après lancer en prod.

**Comment by cyril-r** [comment]
J'ai relancé l'API via le script habituel, j'ai eu pas mal d'errors mais la page 'api running' s'affiche quand même.

```
(Server started, use Ctrl+D to stop and go back to the console...)

[info] Compiling 8 Java sources to /data/MIRMIDON/unstable/mirmidon/LOGIC/api/target/scala-2.10/classes...
[warn] warning: Supported source version 'RELEASE_6' from annotation processor 'org.antlr.v4.runtime.misc.NullUsageProcessor' less than -source '1.7'
[warn] 1 warning
[info] Compiling 24 Java sources to /data/MIRMIDON/unstable/mirmidon/LOGIC/api/target/scala-2.10/classes...
[warn] warning: Supported source version 'RELEASE_6' from annotation processor 'org.antlr.v4.runtime.misc.NullUsageProcessor' less than -source '1.7'
[warn] Note: Some input files use or override a deprecated API.
[warn] Note: Recompile with -Xlint:deprecation for details.
[warn] 1 warning
[info] Compiling 2 Java sources to /data/MIRMIDON/unstable/mirmidon/LOGIC/api/target/scala-2.10/classes...
[warn] warning: Supported source version 'RELEASE_6' from annotation processor 'org.antlr.v4.runtime.misc.NullUsageProcessor' less than -source '1.7'
[warn] 1 warning
[info] play - database [default] connected at jdbc:postgresql://127.0.0.1:5432/mirmidon_unstable?searchpath=LOGIC
[info] application - DRMAA inactive
[error] application - scheduler was not defined. Please verify configuration entry table
[info] application - Application has started
[info] play - Application started (Dev)

--- (RELOAD) ---

[error] application - scheduler was not defined. Please verify configuration entry table
[error] application - None ftp server port was settled
[error] application - None ftp server port was settled
[info] application - Application has stopped
[info] play - database [default] connected at jdbc:postgresql://127.0.0.1:5432/mirmidon_unstable?searchpath=LOGIC
[info] application - DRMAA inactive
[error] application - scheduler was not defined. Please verify configuration entry table
[info] application - Application has started
[info] play - Application started (Dev)
[info] application - Demo User inserted
[info] application - Viewer User inserted
[info] application - Configuration keys inserted
```

---

Lors d'un PUT /database/populate j'obtiens : 

```
{"errors":[{"message":"org.apache.sis.storage.DataStoreException: Unable to initialize WPS client.","code":"02"}]}
```

(note que d'habitude je ne fais pas de database/populate ?)

**Comment by rchailan** [comment]
et si tu relances l'api maintenant ? - Le probleme WPS c'est avec @fretif qu'il faut voir mais je pense que c'est normal.

**Comment by cyril-r** [comment]
```
Starting Play!
[info] Loading project definition from /data/MIRMIDON/unstable/mirmidon/LOGIC/api/project
[info] Set current project to Mirmidon-Logic (in build file:/data/MIRMIDON/unstable/mirmidon/LOGIC/api/)

--- (Running the application from SBT, auto-reloading is enabled) ---

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/play-2.2.2-unstable/repository/local/ch.qos.logback/logback-classic/1.0.13/jars/logback-classic.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/play-2.2.2-unstable/framework/../repository/cache/org.slf4j/slf4j-jdk14/jars/slf4j-jdk14-1.6.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[info] play - Listening for HTTP on /0.0.0.0:9082

(Server started, use Ctrl+D to stop and go back to the console...)

[info] play - database [default] connected at jdbc:postgresql://127.0.0.1:5432/mirmidon_unstable?searchpath=LOGIC
[info] application - Workload Scheduler = SGE
[info] application - DRMAA inactive: unsatisfied link error
[error] application - Can't load library: /data/MIRMIDON/unstable/mirmidon/LOGIC/core/drmaa-jni/target/libDrmaaJNI.so
[info] application - Application has started
[info] play - Application started (Dev)
```

**Comment by rchailan** [comment]
Il y a toujours un probleme car Drmaa n'est pas loadé : 
[error] application - Can't load library: /data/MIRMIDON/unstable/mirmidon/LOGIC/core/drmaa-jni/target/libDrmaaJNI.so
Je vais chercher. ce n'est plus bloquant pour vous pour le moment.

**Comment by cyril-r** [comment]
Ok pas de problème, bonne chance!

**Comment by rchailan** [comment]
Je tente un clean install avec maven (drmaa n'était plus compilée en fait. Je te fais signe quand tu peux retenter.)

**Comment by cyril-r** [comment]
vu, j'attends.

**Comment by rchailan** [comment]
Il nous faut l'aide du grand sage @fretif (et la nuit porte conseil donc on laisse ca à demain)  :

 /opt/maven-3.0.5/bin/mvn clean install -Pcluster
------->

[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Failure executing javac, but could not parse the error:

The system is out of resources.
Consult the following stack trace for details.
java.lang.OutOfMemoryError: PermGen space
    at com.sun.tools.javac.main.JavaCompiler.<init>(JavaCompiler.java:353)
    at com.sun.tools.javac.main.JavaCompiler.instance(JavaCompiler.java:88)
    at com.sun.tools.javac.main.Main.compile(Main.java:424)
    at com.sun.tools.javac.main.Main.compile(Main.java:353)
    at com.sun.tools.javac.main.Main.compile(Main.java:342)
    at com.sun.tools.javac.main.Main.compile(Main.java:333)
    at com.sun.tools.javac.Main.compile(Main.java:94)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcess(JavacCompiler.java:554)
    at org.codehaus.plexus.compiler.javac.JavacCompiler.compile(JavacCompiler.java:161)
    at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:605)
    at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:128)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)

[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Mirmidon Core ..................................... SUCCESS [0.411s]
[INFO] Mirmidon DRMAA JNI ................................ SUCCESS [4.836s]
[INFO] Mirmidon Format ................................... SUCCESS [1.400s]
[INFO] Mirmidon I/O ...................................... SUCCESS [0.015s]
[INFO] Mirmidon I/O ASCII ................................ SUCCESS [0.018s]
[INFO] I/O Core ASCII .................................... SUCCESS [0.675s]
[INFO] Mirmidon I/O NetCDF ............................... SUCCESS [0.019s]
[INFO] I/O Core NetCDF ................................... SUCCESS [1.706s]
[INFO] Mirmidon Converters ............................... SUCCESS [4.157s]
[INFO] Mirmidon Utility .................................. SUCCESS [0.015s]
[INFO] System Tools ...................................... SUCCESS [0.590s]
[INFO] Mirmidon I/O Core ................................. SUCCESS [1.081s]
[INFO] Mirmidon Coverage ................................. SUCCESS [2.669s]
[INFO] I/O TimeSeries ASCII .............................. SUCCESS [3.420s]
[INFO] I/O Fieldsite NetCDF .............................. SUCCESS [3.336s]
[INFO] I/O Symphonie NetCDF .............................. SUCCESS [2.574s]
[INFO] I/O WaveWatch III NetCDF .......................... SUCCESS [0.943s]
[INFO] I/O ECMWF Model NetCDF ............................ SUCCESS [2.517s]
[INFO] Mirmidon Operation ................................ SUCCESS [3.208s]
[INFO] Mirmidon OGC Client ............................... SUCCESS [2.578s]
[INFO] Template Core ..................................... SUCCESS [0.950s]
[INFO] Mirmidon Explorer ................................. FAILURE [2.897s]
[INFO] Mirmidon Aggregator ............................... SKIPPED
[INFO] Mirmidon Configuration Builder .................... SKIPPED
[INFO] Symphonie Model Builder ........................... SKIPPED
[INFO] Telemac Model Builder ............................. SKIPPED
[INFO] Wave Watch III Model Builder ...................... SKIPPED
[INFO] Testor Model Builder .............................. SKIPPED
[INFO] Mirmidon Cstl Integration ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

**Comment by rchailan** [comment]
@cyril-r  Est-ce que le re-start de l'API après recompilation de CORE affiche toujours un probleme Drmaa ?
merci

**Comment by cyril-r** [comment]
Apparemment oui:

Edit, lu trop vite, le problème de session n'est pas lié a drmaa?

```
--- (RELOAD) ---

[error] application - The session has not been initialized or exit() has already been called
[info] application - Application has stopped
[info] play - database [default] connected at jdbc:postgresql://127.0.0.1:5432/mirmidon_unstable?searchpath=LOGIC
[info] application - Workload Scheduler = SGE
[info] application - DRMAA inactive
[error] application - The session has not been initialized or exit() has already been called
[info] application - Application has started
[info] play - Application started (Dev)
```

**Comment by rchailan** [comment]
je vois marqué "reload". Le workflow pour tester si il y a toujours erreur c'est down toute l'api. Puis play run comme tu fais normalement. Merci de m'indiquer si tu as toujours l'erreur que tu viens de reporter.

**Comment by cyril-r** [comment]
Il semblerait que ce soit bon, Drmaa inactive c'est voulu?

```
Starting Play!
[info] Loading project definition from /data/MIRMIDON/unstable/mirmidon/LOGIC/api/project
[info] Set current project to Mirmidon-Logic (in build file:/data/MIRMIDON/unstable/mirmidon/LOGIC/api/)

--- (Running the application from SBT, auto-reloading is enabled) ---

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/play-2.2.2-unstable/repository/local/ch.qos.logback/logback-classic/1.0.13/jars/logback-classic.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/play-2.2.2-unstable/framework/../repository/cache/org.slf4j/slf4j-jdk14/jars/slf4j-jdk14-1.6.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[info] play - Listening for HTTP on /0.0.0.0:9082

(Server started, use Ctrl+D to stop and go back to the console...)

[info] play - database [default] connected at jdbc:postgresql://127.0.0.1:5432/mirmidon_unstable?searchpath=LOGIC
[info] application - Workload Scheduler = SGE
DrmaaJNI object created
[info] application - DRMAA inactive
[error] application - The session has not been initialized or exit() has already been called
[info] application - Application has started
[info] play - Application started (Dev)

```

**Comment by rchailan** [comment]
Ok seems better. Non normalement ca ne devrait pas marqué ça mais j'ai du me tromper quelque part je vérifie.

**Comment by rchailan** [comment]
Should be ok by now. J'ai pushé un fix. (dernier reboot de l'api stp pour vérifier). Merci

**Comment by cyril-r** [comment]
:+1: 

```
Starting Play!
[info] Loading project definition from /data/MIRMIDON/unstable/mirmidon/LOGIC/api/project
[info] Set current project to Mirmidon-Logic (in build file:/data/MIRMIDON/unstable/mirmidon/LOGIC/api/)

--- (Running the application from SBT, auto-reloading is enabled) ---

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/play-2.2.2-unstable/repository/local/ch.qos.logback/logback-classic/1.0.13/jars/logback-classic.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/play-2.2.2-unstable/framework/../repository/cache/org.slf4j/slf4j-jdk14/jars/slf4j-jdk14-1.6.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[info] play - Listening for HTTP on /0.0.0.0:9082

(Server started, use Ctrl+D to stop and go back to the console...)

[info] Compiling 1 Java source to /data/MIRMIDON/unstable/mirmidon/LOGIC/api/target/scala-2.10/classes...
[warn] warning: Supported source version 'RELEASE_6' from annotation processor 'org.antlr.v4.runtime.misc.NullUsageProcessor' less than -source '1.7'
[warn] 1 warning
[info] play - database [default] connected at jdbc:postgresql://127.0.0.1:5432/mirmidon_unstable?searchpath=LOGIC
[info] application - Workload Scheduler = SGE
DrmaaJNI object created
[info] application - Application has started
[info] play - Application started (Dev)
```

**Comment by rchailan** [comment]
cool !

**Comment by cyril-r** [comment]
Il semblerait y avoir un problème (encore).

Lors d'un redéploiement de code sur le répertoire de travail (/data/MIRMIDON/unstable/mirmidon),
au premier démarrage de l'API, voici ce qui se passe:

```
Starting Play!
[info] Loading project definition from /data/MIRMIDON/unstable/mirmidon/LOGIC/api/project

[info] Set current project to Mirmidon-Logic (in build file:/data/MIRMIDON/unstable/mirmidon/LOGIC/api/)
[info] Updating {file:/data/MIRMIDON/unstable/mirmidon/LOGIC/api/}Mirmidon-Logic...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.

--- (Running the application from SBT, auto-reloading is enabled) ---

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/play-2.2.2-unstable/repository/local/ch.qos.logback/logback-classic/1.0.13/jars/logback-classic.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/play-2.2.2-unstable/framework/../repository/cache/org.slf4j/slf4j-jdk14/jars/slf4j-jdk14-1.6.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[info] play - Listening for HTTP on /0.0.0.0:9082

(Server started, use Ctrl+D to stop and go back to the console...)


[info] Compiling 4 Scala sources and 85 Java sources to /data/MIRMIDON/unstable/mirmidon/LOGIC/api/target/scala-2.10/classes...
[warn] warning: Supported source version 'RELEASE_6' from annotation processor 'org.antlr.v4.runtime.misc.NullUsageProcessor' less than -source '1.7'
[warn] Note: Some input files use or override a deprecated API.
[warn] Note: Recompile with -Xlint:deprecation for details.
[warn] Note: Some input files use unchecked or unsafe operations.
[warn] Note: Recompile with -Xlint:unchecked for details.
[warn] 1 warning
[info] play - database [default] connected at jdbc:postgresql://127.0.0.1:5432/mirmidon_unstable?searchpath=LOGIC
[info] application - Workload Scheduler = SGE
[info] application - DRMAA inactive: unsatisfied link error
[error] application - Can't load library: /data/MIRMIDON/unstable/mirmidon/LOGIC/core/drmaa-jni/target/libDrmaaJNI.so
[info] application - Application has started
[info] play - Application started (Dev)

--- (RELOAD) ---

[info] application - Workload Scheduler = SGE
[error] application - 

! @6l0hgene9 - Internal server error, for (GET) [/assets/stylesheets/bootstrap-responsive.min.css] ->

play.api.UnexpectedException: Unexpected exception[NoClassDefFoundError: Could not initialize class org.ggf.drmaa.DrmaaJNI]
        at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:152) ~[play_2.10.jar:2.2.2]
        at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) ~[play_2.10.jar:2.2.2]
        at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
        at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) ~[play_2.10.jar:2.2.2]
        at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) ~[play_2.10.jar:2.2.2]
        at scala.util.Success.flatMap(Try.scala:200) ~[scala-library.jar:na]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.ggf.drmaa.DrmaaJNI
        at org.ggf.drmaa.sge.SessionImpl.<init>(SessionImpl.java:39) ~[mirmidon-drmaa-jni-1.0-UNSTABLE.jar:na]
        at org.ggf.drmaa.sge.SessionFactoryImpl.getSession(SessionFactoryImpl.java:36) ~[mirmidon-drmaa-jni-1.0-UNSTABLE.jar:na]
        at util.SingletonDrmaa.<init>(SingletonDrmaa.java:24) ~[na:na]
        at util.SingletonDrmaa.getInstance(SingletonDrmaa.java:38) ~[na:na]
        at util.Global.onStop(Global.java:33) ~[na:na]
        at play.core.j.JavaGlobalSettingsAdapter.onStop(JavaGlobalSettingsAdapter.scala:22) ~[play_2.10.jar:2.2.2]
[error] application - 

! @6l0hgene9 - Internal server error, for (GET) [/assets/stylesheets/bootstrap.min.css] ->

play.api.UnexpectedException: Unexpected exception[NoClassDefFoundError: Could not initialize class org.ggf.drmaa.DrmaaJNI]
        at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:152) ~[play_2.10.jar:2.2.2]
        at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) ~[play_2.10.jar:2.2.2]
        at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
        at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) ~[play_2.10.jar:2.2.2]
        at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) ~[play_2.10.jar:2.2.2]
        at scala.util.Success.flatMap(Try.scala:200) ~[scala-library.jar:na]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.ggf.drmaa.DrmaaJNI
        at org.ggf.drmaa.sge.SessionImpl.<init>(SessionImpl.java:39) ~[mirmidon-drmaa-jni-1.0-UNSTABLE.jar:na]
        at org.ggf.drmaa.sge.SessionFactoryImpl.getSession(SessionFactoryImpl.java:36) ~[mirmidon-drmaa-jni-1.0-UNSTABLE.jar:na]
        at util.SingletonDrmaa.<init>(SingletonDrmaa.java:24) ~[na:na]
        at util.SingletonDrmaa.getInstance(SingletonDrmaa.java:38) ~[na:na]
        at util.Global.onStop(Global.java:33) ~[na:na]
        at play.core.j.JavaGlobalSettingsAdapter.onStop(JavaGlobalSettingsAdapter.scala:22) ~[play_2.10.jar:2.2.2]

```

Et l'API ne démarre pas.

Si je redémarre à nouveau l'API, voici ce qui se passe : 

```
Starting Play!
[info] Loading project definition from /data/MIRMIDON/unstable/mirmidon/LOGIC/api/project
[info] Set current project to Mirmidon-Logic (in build file:/data/MIRMIDON/unstable/mirmidon/LOGIC/api/)

--- (Running the application from SBT, auto-reloading is enabled) ---

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/play-2.2.2-unstable/repository/local/ch.qos.logback/logback-classic/1.0.13/jars/logback-classic.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/play-2.2.2-unstable/framework/../repository/cache/org.slf4j/slf4j-jdk14/jars/slf4j-jdk14-1.6.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[info] play - Listening for HTTP on /0.0.0.0:9082

(Server started, use Ctrl+D to stop and go back to the console...)

[info] play - database [default] connected at jdbc:postgresql://127.0.0.1:5432/mirmidon_unstable?searchpath=LOGIC
[info] application - Workload Scheduler = SGE
[info] application - DRMAA inactive: unsatisfied link error
[error] application - Can't load library: /data/MIRMIDON/unstable/mirmidon/LOGIC/core/drmaa-jni/target/libDrmaaJNI.so
[info] application - Application has started
[info] play - Application started (Dev)

```

Et cette fois-ci l'API démarre (sans Drmaa).

**Comment by rchailan** [comment]
Faut que je regarde avec toi à coté pcq à distance c'est un peu le calvaire là. Je soupconne un comportement normal mais on vérifiera demain.

**Comment by rchailan** [comment]
Par contre je répète : le problème au RELOAD est NORMAL ! on a vu hier avec Fabien on ne peut pas faire autrement. C'est pour ca que l'on souhaité avoir l'API en production (pour ne pas qu'elle recompile à la volée, ce qui engendre le probleme drmaa).

**Comment by cyril-r** [comment]
Passage de play! en mode prod.
Scripts mis à jour.

**Comment by cyril-r** [comment]
Suite du ticket #30 

Au restart API: 

```
2015-01-23 13:57:03,699 - [ERROR] - from application in main 
Can't load library: /data/MIRMIDON/unstable/mirmidon/LOGIC/core/drmaa-jni/target/libDrmaaJNI.so
```

Edit: le fichier n'existe pas, recompile nécessaire?

**Comment by rchailan** [comment]
tu as redéployé le noeud ? 
oui là il faut déployer tout le core à mon avis (commande maven). C'est certaienemtn ce qui a fait planter le database populator d'ailleurs...

**Comment by cyril-r** [comment]
non je n'ai pas redéployé le noeud (c'es en projet pour la fin de la journée afin de tester les nouveaux scripts de déploiement initiaux).

Je vais relancer une compilation.

**Comment by cyril-r** [comment]
Après recompilation, pas de mention de Drmaa, je suppose donc que c'est ok?

```
2015-01-23 14:15:12,311 - [INFO] - from play in main 
database [default] connected at jdbc:postgresql://127.0.0.1:5432/mirmidon_unstable?searchpath=LOGIC

2015-01-23 14:15:13,703 - [INFO] - from application in main 
Workload Scheduler = SGE

2015-01-23 14:15:14,115 - [INFO] - from application in main 
Application has started

2015-01-23 14:15:14,123 - [INFO] - from play in main 
Application started (Prod)

2015-01-23 14:15:14,259 - [INFO] - from play in main 
Listening for HTTP on /0.0.0.0:9082

```

**Comment by cyril-r** [comment]
Je ferme le ticket, pas de problème Drmaa avec DB fonctionnelle.
