### ISSUE TITLE
Refactor du workflow de déploiement pour mirmidon_unstable

### ISSUE THREAD

**Issue by cyril-r** [MirmidonDev/mirmidon_unstable#27]
Suite demande @rc-34 et @fretif , on va adopter un système de mise en prod découplé des push sur le GIT.

Une commande / bouton sera mis en place pour pousser manuellement la révision HEAD de mirmidon_unstable du git sur le répertoire de travail mirmidon_unstable.

Avant le déploiement, l'instance de Play! sera killée, on relancera play! une fois le nouveau code en place.

On envisage la mise en place d'un cronjob qui fasse une bascule par jour automatiquement.

**Comment by cyril-r** [comment]
Done.

Ce qu'il faut retenir : 

| Effet Désiré | Commande |
| --- | --- |
| Mise à jour du code (entraine arrêt et redémarrage de l'API) | `/scripts/update_mirmidon_unstable.sh` |
| Démarrage/Redémarrage API | `/scripts/start_api.sh` |
| Arrêt API | `/scripts/stop_api.sh` |
| Console Constellation | `screen -R constellation` |
| Logs Play! | `/scripts/play_logs.sh` |

Le hook du repository git à été désactivé.

**Comment by rchailan** [comment]
Je pense que le hook n'est pas encore désactivé : 

 rchailan$ git push origin master
Counting objects: 6, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 632 bytes | 0 bytes/s, done.
Total 6 (delta 4), reused 0 (delta 0)
remote: hooks/post-receive: line 12: syntax error near unexpected token `elif'
remote: hooks/post-receive: line 12:`    elif [ "testing" == "$branch" ]; then'
To romain@p4x-650.gateworld.fr:/data/REPOSITORY/GIT/mirmidon.git
   3ec78d5..32f4585  master -> master

**Comment by cyril-r** [comment]
Faute de frappe, corrigé.
