### ISSUE TITLE
Aggragations refactor

### ISSUE THREAD

**Issue by jhuon** [MirmidonDev/mirmidon_unstable#28]
Comme vue hier, il faudrait refactoriser l'api de l'aggregator pour être consistant :

[GET] /aggregations?limit=5&offset=1&status=pending
Obtenir une liste des agrégations selon des filtres définis (limit/offset/status)

[GET] /aggregations/formats
Obtenir la liste des formats supportés par l'API

[POST] /aggregations/netcdf-ecmwf
Créer une agrégation au format ECMWF

**Comment by fretif** [comment]
J'ai fait une v1.0.
Je vais rajouter un filtre par phénomène et un filtre par date de début, date de fin qui servira pour l'explorer

**Comment by rchailan** [comment]
@fretif : as tu toujours besoin que je fasse les routes pour 
/layers => obtenir les layers (ou phenomena)
/layers/<id>/date => obtenir les ranges de date continue
/layers/<id>/periodicity => obtenir les time steps du phenomene 

Ou bien on se servira de ce que vous/tu avez/as fait ?

**Comment by fretif** [comment]
Oui, appelle la /phenomena
Je m'occuperai de remplir le code

---- Le ven., 23 janv. 2015 10:27:22 +0100 Romain Chailan &lt;notifications@github.com&gt; a écrit ---- 

@fretif : as tu toujours besoin que je fasse les routes pour 
 /layers =&gt; obtenir les layers (ou phenomena)
 /layers//date =&gt; obtenir les ranges de date continue
 /layers//periodicity =&gt; obtenir les time steps du phenomene 
 Ou bien on se servira de ce que vous/tu avez/as fait ? 
 —
Reply to this email directly or view it on GitHub.

_.-~-._.-~-._.-~-._.-~-._.-~-._ 
PhD. Fabien Rétif
Géosciences Montpellier
UMR 5243 - CC 60
Universite Montpellier II
Bat 22 - Bureau 468
Place Eugène Bataillon
34095 Montpellier Cedex 5
France
Tel : +33 (0)4.67.14.35.85
_.-~-._.-~-._.-~-._.-~-._.-~-._
