### ISSUE TITLE
Refactor json (list + fieldsite)

### ISSUE THREAD

**Issue by rchailan** [MirmidonDev/mirmidon_unstable#29]
@MirmidonDev/team 
Selon les recommandations de @fretif  j'ai changé les valeurs des json retournées quand on accède à une liste d'éléments (par exemple la liste des fieldsites, ou la liste des commandes, notifications).

Désormais dans une telle situation l'API renvoie un tableau de json par exe (il n'y a qu'un fieldsite là): 

``` json
[
    {
        "id": 1,
        "name": "megagol",
        "creation_date": "Thu Jan 22 12:51:35 CET 2015",
        "envelope": {
            "crs_code": "coucou",
            "x_min": 31,
            "x_max": 45,
            "y_min": -5,
            "y_max": 17
        }
    }
]
```

Aussi vous noterez que désormais tous les attributs référensq de l'objet accédé ne sont pas précédés de son propre type. Par exemple il n'y a plus "fieldsite_id" mais simplement "id". Il en va de même pour d'autres attributs qui trainaient comme "command_creation_date" qui devient "creation_date" lorsqu'on accède à une commande. 

Désolé, normalement avec une telle sémantique on devrait être pleinement cohérents... Ca ce peut que certains de vos fonctions buggues un peu dans un premier temps :8ball:

**Comment by cyril-r** [comment]
Client mis à jour. - ok
