### ISSUE TITLE
Fieldsites HS

### ISSUE THREAD

**Issue by cyril-r** [MirmidonDev/mirmidon_unstable#30]
Lors d'un HTTP GET /fieldsites, on obtiens:

```
Oops, an error occured
This exception has been logged with id 6l15j5ih9.
```

Lors d'un HTTP PUT sur /fieldsites, on obtiens:

``` json
{
    "errors": [
        {
            "message": "Query threw SQLException:ERROR: column t0.envelope does not exist\n  Position : 60 \r\nBind values:[21,megagol4] \r\nQuery was:\r\nselect t0.id as c0, t0.name as c1, t0.creation_date as c2, t0.envelope as c3, t0.muser as c4 from mfield_site t0 where muser = ?  and t0.name = ?  \r\n\r\n",
            "code": "4"
        }
    ]
}
```

**Comment by rchailan** [comment]
peux tu me donner le workflow exact ? je n'arrive pas à reproduire le probleme en local.

Par ailleurs à la lecture des logs j'ai l'impression qu'il y a une corruption de la db (je pense à l'option -Ddown d'hier ..) ?

Le meilleur moyen pour etre sur qu'on est dans le vrai c'est de 
- Dropper le schéma via admin postgres. 
- Lancer play en "run" à la main. 
- Faire un accès via le web-browser. 
- Cliquer sur needs evolution. (a conséquence de creer la base)
- Fermer play
- Re lancer en start.
- retester les push / etc. 

Comme ca on est sur d'avoir un DB correcte.

Est ce que tu es ok pour ca ?

Par contre je vais voir pourquoi je n'ai pas catché l'exception sur le GET /fieldsites. Ce n'est pas normal. Et par contre la deuxieme exception est bien gérée.

**Comment by cyril-r** [comment]
Le workflow est simple : je me log, je fait un list fieldsites et ça ne fonctionne pas.

Je vais supprimer la db et faire ce que tu à dis, en espérant que le problème ne se reproduise pas vu la procédure assez lourde pour fixer.

**Comment by cyril-r** [comment]
J'ai droit à : PSQLException: ERROR: relation "play_evolutions" does not exist Position : 64

Lors du play run

**Comment by cyril-r** [comment]
Ok trouvé le problème et corrigé.

L'api se lance, dans le log j'ai : 

```
2015-01-23 12:15:18,399 - [INFO] - from application in main 
DRMAA inactive
```

Je support qu'il faut recompiler?

Pour les fieldsites ça semble ok.

**Comment by rchailan** [comment]
Cool pr les fieldsites. Ca m'étonnait aussi.
Pour la recompile : Non. Je pense que cela vient du fait que tu dois faire le database/populator pour renseigner la table configuration entry dans laquelle on spécifie le scheduler avec lequel on bosse.

**Comment by cyril-r** [comment]
Ok le populator me retourne ceci: (PUT /database/populate)

``` json
{
    "errors": [
        {
            "message": "org.apache.sis.storage.DataStoreException: Unable to initialize WPS client.",
            "code": "02"
        }
    ]
}
```

normal?

**Comment by rchailan** [comment]
pour l'erreur /database/populate faut voir avec @fretif

**Comment by cyril-r** [comment]
Fieldsites fonctionnels.

**Comment by cyril-r** [comment]
Après recompilation et avoir relancé l'api, le problème drmaa semble réglé mais l'erreur est de retour (suite ticket #26 )

so sad :(

**Comment by rchailan** [comment]
Attends, tu pars dans tous les sens là... je ne comprends plus rien. ouvert fermé ouvert ?? 
- 0 déployer core
- 1 schéma droppé
- 2 run play + start constellation
- 3 construire db (evolution)
- 4 /database/populate
- 5 fermer play
- 6 start play (avec constellation toujours opérationnel)

**Comment by cyril-r** [comment]
Je suis aussi dans le trouble, depuis le passage en mode prod, on à des comportements que l'on avait pas avant.

Si je comprends bien, à chaque recompilation de l'api, il faudra refaire ces 6 étapes pour que ça fonctionne à nouveau?

**Comment by cyril-r** [comment]
Tout à été refait comme décrit dans ta procédure, l'api tourne et les fieldsites fonctionnent.

Je reste quand même étonné qu'il faille dropper le schéma public à la main (et le recréer vide) pour que cela fonctionne.

**Comment by rchailan** [comment]
Je ne pense pas qu'il faille le faire à chaque fois. Sinon c'est qu'il y a un probleme. On regardera dans les jours à venir.

**Comment by cyril-r** [comment]
Je confirme qu'à chaque update du code (entrainant sa recompilation), le database populator se mets dans les choux (on dirait qu'il fait la moitié du boulot).

Obligé de réaliser la procédure en 6 étapes pour cleaner la DB à la main.
Ca peut faire l'objet d'un autre ticket, si fieldsites déconne c'est directement lié à ce problème, mais lorsque la db est correcte les fieldsites sont OK.

Je ferme ce ticket on en fera un autre pour populator.
