### ISSUE TITLE
Database populator renvoie un code 02

### ISSUE THREAD

**Issue by cyril-r** [MirmidonDev/mirmidon_unstable#31]
Après un appel sur PUT /database/populate, j'obtiens une sortie avec erreur:

```
{
    "errors": [
        {
            "message": "org.apache.sis.storage.DataStoreException: Unable to initialize WPS client.",
            "code": "02"
        }
    ]
}
```

**Comment by fretif** [comment]
L'erreur parle d'elle même non ? est-ce que le constellation est lancé ? 

---- Le ven., 23 janv. 2015 14:06:00 +0100 cyril-r&lt;notifications@github.com&gt; a écrit ---- 

Après un appel sur PUT /database/populate, j'obtiens une sortie avec erreur:
 { "errors": [ { "message": "org.apache.sis.storage.DataStoreException: Unable to initialize WPS client.", "code": "02" } ] }  —
Reply to this email directly or view it on GitHub.

_.-~-._.-~-._.-~-._.-~-._.-~-._ 
PhD. Fabien Rétif
Géosciences Montpellier
UMR 5243 - CC 60
Universite Montpellier II
Bat 22 - Bureau 468
Place Eugène Bataillon
34095 Montpellier Cedex 5
France
Tel : +33 (0)4.67.14.35.85
_.-~-._.-~-._.-~-._.-~-._.-~-._

**Comment by cyril-r** [comment]
Yes, mais entre temps j'ai recompilé l'API pour fixer un pb drmaa.

désormais lorsque l'on lance le populator l'erreur est différente:

```
Oops, an error occured
This exception has been logged with id 6l16i9fa0.
```

Par contre tout semble fonctionner, peut-être qu'il n'est donc pas nécessaire de refaire un populator.

Dans ce cas la autant renvoyer un message disant que c'est inutile ou n'aboutira pas?

**Comment by cyril-r** [comment]
Je pense que le mieux est que tu passe rapidement lundi pour voir ce qui se produit lorsque l'on lance constellation (j'ai vu des erreurs passer) et que l'on appelle le populator.

On peut faire ça?

**Comment by cyril-r** [comment]
Le problème de constellation à été corrigé via patch temporaire.

Ce qui à été fait:

Remplacement du constellation de la build mirmidon par le constellation de git Géomatys

```
#!/bin/bash
mkdir /data/fix-constellation/
cd /data/fix-constellation
/usr/local/bin/git clone git://github.com/Geomatys/constellation.git --depth 1
cd constellation
/opt/maven-3.0.5/bin/mvn clean install -DskipTests
```
