### ISSUE TITLE
Notifications delete non fonctionnel

### ISSUE THREAD

**Issue by cyril-r** [MirmidonDev/mirmidon_unstable#32]
Sur le module notifications, les appels suivants : 

DELETE /notifications
DELETE /notifications/<notification_id>

Ne fonctionnent pas, en retour j'obtiens toujours une erreur 400 de type:

Bad request
For request 'DELETE /notifications/5' [Invalid Json]

Dans mon exemple, je tente de supprimer la notification 5, via HTTP DELETE, je n'envoie donc pas de JSON vu qu'il n'y en à pas besoin, et je me fais jeter.

**Comment by rchailan** [comment]
Je n'ai pas cette erreur. Attention à ne pas mettre dans le header de ta requete le content-type json. Sinon il s'attend à avoir du json. At least 

``` json
{}
```
