### ISSUE TITLE
Notifications clear/unstick non fonctionnels

### ISSUE THREAD

**Issue by cyril-r** [MirmidonDev/mirmidon_unstable#33]
Sur le module notifications, les routes suivantes:

GET /notifications/clear
GET /notifications/<notification_id>/clear
GET /notifications/unstick
GET /notifications/<notification_id>/unstick

Renvoient toutes une erreur 500 du style:

Oops, an error occured
This exception has been logged with id 6l28pn0ba.

Exemple de requête : 

GET /notifications/5/clear (via postman et GUI pareil, la notification existe bien).

**Comment by rchailan** [comment]
Fix pushed.

**Comment by cyril-r** [comment]
Fonctionne comme attendu.
