### ISSUE TITLE
Notifications : Problème de droits d'affichage

### ISSUE THREAD

**Issue by cyril-r** [MirmidonDev/mirmidon_unstable#34]
Lorsque j'établis la connexion websocket et envoie le token, je récupère une liste de notifications, mais cette liste contiens des notifications d'autres utilisateurs.

Lorsque j'ajoute une notification via postman, je la vois apparaitre sur la GUI (via websockets), alors que la GUI et postman ont chacun leur user propre.

On a donc sur la GUI des notifications qui n'appartiennent pas à l'user courant, et qui ne peuvent pas être clearés ni supprimées (ce qui est normal).

Lorsque je fais un GET /notifications pour vérifier, j'obtiens bien la liste des notifications mais uniquement celles de l'user connecté.

Le problème doit probablement se situer au niveau de websockets et sa manière de renvoyer les notifications.

**Comment by rchailan** [comment]
Fix tested and pushed (67dffae..f4fe76f).
