### ISSUE TITLE
Problème à la création d'une aggregation

### ISSUE THREAD

**Issue by cyril-r** [MirmidonDev/mirmidon_unstable#35]
## Ce ticket est une synthèse des deux mails que j'ai envoyés à Fabien hier.

Lors d'une tentative de créer une aggrégation:

```
POST http://p4x-650.gateworld.fr:9082/aggregations/netcdf-ecmwf 
```

Avec le json suivant:

``` json
{
    "name": "ECMWF aggregation",
    "description": "The data is the atmospheric forcing",
    "phenomena": [
        "wind10m",
        "surface-pressure",
        "surface-sensible-heat-flux",
        "surface-latent-heat-flux",
        "air-temperature2m",
        "dewpoint-temperature2m",
        "surface-solar-radiation-downwards",
        "surface-thermal-radiation-downwards",
        "surface-solar-radiation",
        "surface-thermal-radiation",
        "total-rain"
    ],
    "files_url_protocol": "file",
    "files": [
        "/test/MED.20130303.nc",
        "/test/MED.20130304.nc",
        "/test/MED.20130305.nc",
        "/test/MED.20130306.nc",
        "/test/MED.20130307.nc"
    ]
} 
```

J'ai ici tenté d'utiliser les fichiers uploadés sur le FTP directement, sans succès, voici le retour:

``` json
{
    "errors": [
        {
            "message": "Error while adding geographic metadata of the aggregation : Reading /tmp/3d3f4e26-5fc8-4d29-b3fd-56521cfd4a171567774510409912356.nc at 8 file length = 8",
            "code": "02"
        }
    ]
} 
```

Pourtant, en faisant un HTTP GET /ftp, les fichiers sont bien listés:

``` json
{
    "FTP": [
        {
            "test": [
                "MED.20130305.nc",
                "MED.20130307.nc",
                "MED.20130303.nc",
                "MED.20130304.nc",
                "MED.20130306.nc"
            ]
        },
        {
            "tt": []
        }
    ]
} 
```

Suite à cela, j'ai tenté la même chose en exposant les fichiers sur un serveur, et j'ai changé **file** par **http** (en mettant à jour les URLs).

Cette fois-ci ça va plus loin, mais je suis bloqué par l'erreur suivante:

``` json
{
    "errors": [
        {
            "message": "Error while adding the aggregation : ERROR: function st_geometryfromtext(text, integer) does not exist\n Indice : No function matches the given name and argument types. You might need to add explicit type casts.\n  Où : PL/pgSQL function coverages.\"ComputeDefaultExtent\"() line 4 at assignment",
            "code": "02"
        }
    ]
} 
```

**Comment by fretif** [comment]
J'ai ré-installé la base coverage car il y avait un problème. Peux-tu ré-essayer en http. 

---- Le jeu., 29 janv. 2015 10:25:06 +0100 cyril-r&lt;notifications@github.com&gt; a écrit ---- 

Ce ticket est une synthèse des deux mails que j'ai envoyés à Fabien hier.
 Lors d'une tentative de créer une aggrégation:
 POST http://p4x-650.gateworld.fr:9082/aggregations/netcdf-ecmwf  Avec le json suivant:
 { "name": "ECMWF aggregation", "description": "The data is the atmospheric forcing", "phenomena": [ "wind10m", "surface-pressure", "surface-sensible-heat-flux", "surface-latent-heat-flux", "air-temperature2m", "dewpoint-temperature2m", "surface-solar-radiation-downwards", "surface-thermal-radiation-downwards", "surface-solar-radiation", "surface-thermal-radiation", "total-rain" ], "files_url_protocol": "file", "files": [ "/test/MED.20130303.nc", "/test/MED.20130304.nc", "/test/MED.20130305.nc", "/test/MED.20130306.nc", "/test/MED.20130307.nc" ] } 
 J'ai ici tenté d'utiliser les fichiers uploadés sur le FTP directement, sans succès, voici le retour:
 { "errors": [ { "message": "Error while adding geographic metadata of the aggregation : Reading /tmp/3d3f4e26-5fc8-4d29-b3fd-56521cfd4a171567774510409912356.nc at 8 file length = 8", "code": "02" } ] } 
 Pourtant, en faisant un HTTP GET /ftp, les fichiers sont bien listés:
 { "FTP": [ { "test": [ "MED.20130305.nc", "MED.20130307.nc", "MED.20130303.nc", "MED.20130304.nc", "MED.20130306.nc" ] }, { "tt": [] } ] } 
 Suite à cela, j'ai tenté la même chose en exposant les fichiers sur un serveur, et j'ai changé file par http (en mettant à jour les URLs).
 Cette fois-ci ça va plus loin, mais je suis bloqué par l'erreur suivante:
 { "errors": [ { "message": "Error while adding the aggregation : ERROR: function st_geometryfromtext(text, integer) does not exist\n Indice : No function matches the given name and argument types. You might need to add explicit type casts.\n Où : PL/pgSQL function coverages.\"ComputeDefaultExtent\"() line 4 at assignment", "code": "02" } ] } 
 —
Reply to this email directly or view it on GitHub.

_.-~-._.-~-._.-~-._.-~-._.-~-._ 
PhD. Fabien Rétif
Géosciences Montpellier
UMR 5243 - CC 60
Universite Montpellier II
Bat 22 - Bureau 468
Place Eugène Bataillon
34095 Montpellier Cedex 5
France
Tel : +33 (0)4.67.14.35.85
_.-~-._.-~-._.-~-._.-~-._.-~-._

**Comment by cyril-r** [comment]
C'est fait, voila la sortie:

``` json
{
    "errors": [
        {
            "message": "Error while adding the aggregation : ERROR: insert or update on table \"Series\" violates foreign key constraint \"Series_layer_fkey\"\n  Détail : Key (layer)=(wind10m) is not present in table \"Layers\".",
            "code": "02"
        }
    ]
}
```

**Comment by fretif** [comment]
OK, again s'il te plait.

---- Le jeu., 29 janv. 2015 11:03:48 +0100 cyril-r&lt;notifications@github.com&gt; a écrit ---- 

C'est fait, voila la sortie:
 { "errors": [ { "message": "Error while adding the aggregation : ERROR: insert or update on table \"Series\" violates foreign key constraint \"Series_layer_fkey\"\n Détail : Key (layer)=(wind10m) is not present in table \"Layers\".", "code": "02" } ] }
 —
Reply to this email directly or view it on GitHub.

_.-~-._.-~-._.-~-._.-~-._.-~-._ 
PhD. Fabien Rétif
Géosciences Montpellier
UMR 5243 - CC 60
Universite Montpellier II
Bat 22 - Bureau 468
Place Eugène Bataillon
34095 Montpellier Cedex 5
France
Tel : +33 (0)4.67.14.35.85
_.-~-._.-~-._.-~-._.-~-._.-~-._

**Comment by cyril-r** [comment]
Ok, cette fois-ci, pas de sortie, mais un code HTTP 200, c'est bon alors? :+1:

**Comment by cyril-r** [comment]
En fait je ne sait pas:

```
GET /aggregations
```

Retour:

``` json
[]
```

A moins qu'il ne faille attendre.

**Comment by fretif** [comment]
Est-ce que le port du constellation est ouvert sur le micro serveur : 8092 ?

---- Le jeu., 29 janv. 2015 11:12:52 +0100 cyril-r&lt;notifications@github.com&gt; a écrit ---- 

En fait je ne sait pas:
 GET /aggregations  Retour:
 []
 —
Reply to this email directly or view it on GitHub.

_.-~-._.-~-._.-~-._.-~-._.-~-._ 
PhD. Fabien Rétif
Géosciences Montpellier
UMR 5243 - CC 60
Universite Montpellier II
Bat 22 - Bureau 468
Place Eugène Bataillon
34095 Montpellier Cedex 5
France
Tel : +33 (0)4.67.14.35.85
_.-~-._.-~-._.-~-._.-~-._.-~-._

**Comment by cyril-r** [comment]
Il ne l'étais pas (8090 à la place), je viens de l'ajouter et relancer une aggrégation.
Idem (HTTP 200 à la création), rien dans le listing.

**Comment by fretif** [comment]
OK, les 2 aggrégations sont ok. Le client wms les affiche et en couleur svp ! Pour la commande aggrégations, les arguments par défaut du filtre n'affiche aucun résultat. Je pourrais peut être le changer mettre les 10 premiers par exemple ? en attendant donne lui des arguments.

Fabien

---- Le jeu., 29 janv. 2015 11:21:19 +0100 cyril-r&lt;notifications@github.com&gt; a écrit ---- 

Il ne l'étais pas (8090 à la place), je viens de l'ajouter et relancer une aggrégation.
 Idem (HTTP 200 à la création), rien dans le listing.
 —
Reply to this email directly or view it on GitHub.

_.-~-._.-~-._.-~-._.-~-._.-~-._ 
PhD. Fabien Rétif
Géosciences Montpellier
UMR 5243 - CC 60
Universite Montpellier II
Bat 22 - Bureau 468
Place Eugène Bataillon
34095 Montpellier Cedex 5
France
Tel : +33 (0)4.67.14.35.85
_.-~-._.-~-._.-~-._.-~-._.-~-._

**Comment by cyril-r** [comment]
yayyyy!

Ok pour lui filer les arguments, si pas d'arguments oui ce serais pas mal d'avoir par ex les 10 derniers.

Je ferme le ticket vu que le pb est résolu.

**Comment by rchailan** [comment]
:):):):)
