### ISSUE TITLE
FTP : problème de ports pour établissement d'une connexion passive.

### ISSUE THREAD

**Issue by cyril-r** [MirmidonDev/mirmidon_unstable#36]
Lorsque l'on tente de se connecter au FTP de Mirmidon (exposé par play! il me semble), la connexion sur le port **2121** s'établit correctement et le canal de contrôle fonctionne bien.

Cependant lorsqu'il faut lister les répertoires ou initier un transfert, une connexion passive est crée, mais le problème est que le range de ports utilisés par le serveur FTP est pour le moment incertain.

De ce fait il m'est impossible d'ouvrir par exemple un range de 10 ports spécifiques pour les transferts FTP car je ne sait pas à l'avance des quels il s'agit.

De plus les ports ouverts devraient être > 1024 (non privilégiés).

Il faut donc configurer le ftp pour qu'il utilise un range de ports défini à l'avance.

J'ai assigné @rc-34 mais @fretif est au courant, changez l'assignee si besoin.

**Comment by fretif** [comment]
Done. Les passives ports vont de 2300 à 2399

**Comment by cyril-r** [comment]
Ok, mise à jour effectuée sur l'appliance.

La modif sera effective au prochain redéploiement de code.
