### ISSUE TITLE
Recompilation/Redéploiement : Corruption de la DB

### ISSUE THREAD

**Issue by cyril-r** [MirmidonDev/mirmidon_unstable#37]
Lors d'une update de code (mise en prod de la version unstable) et recompilation du core, la DB n'est plus utilisable et doit être supprimée et recrée via une procédure manuelle contraignante (perte de l'automatisation de déploiement de la plateforme).

Le problème à des impacts sur le chargement de Drmaa.

Un second problème à été identifié sur le schéma "coverages" qui serait - semble-t-il - aussi impacté lors d'un redéploy.

Il faut trouver la source du/des problème(s) et revoir le déploiement / mise à jour de la DB ainsi que le database populator.

---

Mention de @rc-34 pour notification.

**Comment by fretif** [comment]
Le problème sur coverages est bien en amont du redéploiement. C'est la manière de créer le schéma qui est à revoir.

Attention, il ne faut pas confondre la plateforme de développement et la plateforme de production. Dans notre cas, les deux sont liés mais il ne faut pas tendre vers une machine de guerre tout automatisé mais plutôt sur une procédure pour déployer la plateforme de développement et une procédure pour déployer celle en production.

On dissociera les deux dès que l'on a assez de recul.

Fabien

---- Le jeu., 29 janv. 2015 11:59:35 +0100 cyril-r&lt;notifications@github.com&gt; a écrit ---- 

Lors d'une update de code (mise en prod de la version unstable) et recompilation du core, la DB n'est plus utilisable et doit être supprimée et recrée via une procédure manuelle contraignante (perte de l'automatisation de déploiement de la plateforme).
 Le problème à des impacts sur le chargement de Drmaa.
 Un second problème à été identifié sur le schéma "coverages" qui serait - semble-t-il - aussi impacté lors d'un redéploy.
 Il faut trouver la source du/des problème(s) et revoir le déploiement / mise à jour de la DB ainsi que le database populator.
  Mention de @rc-34 pour notification.
 —
Reply to this email directly or view it on GitHub.

_.-~-._.-~-._.-~-._.-~-._.-~-._ 
PhD. Fabien Rétif
Géosciences Montpellier
UMR 5243 - CC 60
Universite Montpellier II
Bat 22 - Bureau 468
Place Eugène Bataillon
34095 Montpellier Cedex 5
France
Tel : +33 (0)4.67.14.35.85
_.-~-._.-~-._.-~-._.-~-._.-~-._

**Comment by cyril-r** [comment]
Ok, je suis d'accord pour la différence au niveau de la plateforme dev/prod, j'ai du mal m'exprimer sorry, je parle de la bascule de code sur l'environnement unstable qui est problématique depuis quelques jours.

Vous m'avez demandé de passer play! en mode prod sur l'environnement unstable pour éviter qu'il recompile à la volée le code.
Ce qui impliquais le retrait des hooks du git pour permettre une meilleure maitrise du déploiement du code de mirmidon unstable.

En remplacement, on à un script qui mets à jour mirmidon unstable, que l'on appelle manuellement, et qui devrait plus tard être automatique (on avais parlé d'un refresh de la build unstable tous les soirs à minuit).

Ce qu'il faut c'est que lorsque la build mirmidon unstable est (re)mise à jour, la DB soit utilisable sans devoir intervenir manuellement, comme avant ou seul un database populator suffisait.

Rappel de la procédure donnée par @rc-34 qui est actuellement appliquée a chaque update de code:

```
    Dropper le schéma via admin postgres.
    Lancer play en "run" à la main.
    Faire un accès via le web-browser.
    Cliquer sur needs evolution. (a conséquence de creer la base)
    Fermer play
    Re lancer en start.
    retester les push / etc.
```

**Comment by fretif** [comment]
Voici la procédure automatique à faire lors d'un déploiement en prod :
1. git clone 
2. mvn install du core (rajouter le deploy si l'on veut)
3. Drop le schéma public
4. catalina.sh start
5. play evolutions:apply start (à vérifier que l'on puisse faire les deux en même temps sinon faire le start dans une autre commande).
6. Populator

Fabien

---- Le jeu., 29 janv. 2015 12:28:25 +0100 cyril-r&lt;notifications@github.com&gt; a écrit ---- 

Ok, je suis d'accord pour la différence au niveau de la plateforme dev/prod, j'ai du mal m'exprimer sorry, je parle de la bascule de code sur l'environnement unstable qui est problématique depuis quelques jours.
 Vous m'avez demandé de passer play! en mode prod sur l'environnement unstable pour éviter qu'il recompile à la volée le code.
 Ce qui impliquais le retrait des hooks du git pour permettre une meilleure maitrise du déploiement du code de mirmidon unstable.
 En remplacement, on à un script qui mets à jour mirmidon unstable, que l'on appelle manuellement, et qui devrait plus tard être automatique (on avais parlé d'un refresh de la build unstable tous les soirs à minuit).
 Ce qu'il faut c'est que lorsque la build mirmidon unstable est (re)mise à jour, la DB soit utilisable sans devoir intervenir manuellement, comme avant ou seul un database populator suffisait.
 Rappel de la procédure donnée par @rc-34 qui est actuellement appliquée a chaque update de code:
  Dropper le schéma via admin postgres. Lancer play en "run" à la main. Faire un accès via le web-browser. Cliquer sur needs evolution. (a conséquence de creer la base) Fermer play Re lancer en start. retester les push / etc.  —
Reply to this email directly or view it on GitHub.

_.-~-._.-~-._.-~-._.-~-._.-~-._ 
PhD. Fabien Rétif
Géosciences Montpellier
UMR 5243 - CC 60
Universite Montpellier II
Bat 22 - Bureau 468
Place Eugène Bataillon
34095 Montpellier Cedex 5
France
Tel : +33 (0)4.67.14.35.85
_.-~-._.-~-._.-~-._.-~-._.-~-._

**Comment by cyril-r** [comment]
Ok pour la procédure, j'adapterais le script et ferais les tests rapidement, pour le moment on à besoin de l'API donc ce sera pour le prochain update de code.

Je ferais un retour en temps voulu.

**Comment by cyril-r** [comment]
Problème partiellement réglé par @fretif qui à corrigé a la main les bases coverages.
L'issue est maintenue pour la prochaine milestone.
