### ISSUE TITLE
Aggregation bathy

### ISSUE THREAD

**Issue by cyril-r** [MirmidonDev/mirmidon_unstable#47]
Fabien, 

Lorsque je tente de créer une aggregation de bathymétrie via postman, l'API renvoie un code **200** (OK), l'aggregation est listée dans l'aggregator, mais elle ne possède aucun phénomène.

Dans les logs on voit qu'il y a une erreur.

Voici le json envoyé : 

``` json
{
    "name": "Sirocco bathy",
    "description": "Bathy from sirocco",
    "phenomena": [
        "bathymetry"
    ],
    "file_url_protocol": "file",
    "file": "sirocco.europe.nc"
}
```

Voici le log play!

```
2015-02-12 19:30:32,266 - [INFO] - from application in play-akka.actor.default-dispatcher-21 
[ Aggregator ] No WPS process for the aggregation 'Sirocco bathy' (7).

2015-02-12 19:30:32,616 - [INFO] - from application in play-akka.actor.default-dispatcher-21 
[ Aggregator ] The aggregation 'Sirocco bathy' (7) is completed.

2015-02-12 19:31:10,509 - [ERROR] - from application in play-akka.actor.default-dispatcher-23 
[ Explorer ] Unable to read meta data for the aggregation 'Sirocco bathy' (7)/phenomenon : bathymetry : This file contains none variables in 3 dimensions

2015-02-12 19:31:18,392 - [ERROR] - from application in play-akka.actor.default-dispatcher-21 
[ Explorer ] Unable to read meta data for the aggregation 'Sirocco bathy' (7)/phenomenon : bathymetry : This file contains none variables in 3 dimensions

```

**Comment by fretif** [comment]
Où vois-tu qu'elle n'a pas de phénomènes ? en base de données, elle est bien enregistrée
Par contre effectivement, il y a un problème sur l'explorer. Je me note cela.

---- Le jeu., 12 févr. 2015 20:09:01 +0100 cyril-r &lt;notifications@github.com&gt; a écrit ---- 

Fabien, 
 Lorsque je tente de créer une aggregation de bathymétrie via postman, l'API renvoie un code 200 (OK), l'aggregation est listée dans l'aggregator, mais elle ne possède aucun phénomène.
 Dans les logs on voit qu'il y a une erreur.
 Voici le json envoyé : 
 { "name": "Sirocco bathy", "description": "Bathy from sirocco", "phenomena": [ "bathymetry" ], "file_url_protocol": "file", "file": "sirocco.europe.nc" }
 Voici le log play!
 2015-02-12 19:30:32,266 - [INFO] - from application in play-akka.actor.default-dispatcher-21 [ Aggregator ] No WPS process for the aggregation 'Sirocco bathy' (7). 2015-02-12 19:30:32,616 - [INFO] - from application in play-akka.actor.default-dispatcher-21 [ Aggregator ] The aggregation 'Sirocco bathy' (7) is completed. 2015-02-12 19:31:10,509 - [ERROR] - from application in play-akka.actor.default-dispatcher-23 [ Explorer ] Unable to read meta data for the aggregation 'Sirocco bathy' (7)/phenomenon : bathymetry : This file contains none variables in 3 dimensions 2015-02-12 19:31:18,392 - [ERROR] - from application in play-akka.actor.default-dispatcher-21 [ Explorer ] Unable to read meta data for the aggregation 'Sirocco bathy' (7)/phenomenon : bathymetry : This file contains none variables in 3 dimensions  —
Reply to this email directly or view it on GitHub.

_.-~-._.-~-._.-~-._.-~-._.-~-._ 
PhD. Fabien Rétif
Géosciences Montpellier
UMR 5243 - CC 60
Universite Montpellier II
Bat 22 - Bureau 468
Place Eugène Bataillon
34095 Montpellier Cedex 5
France
Tel : +33 (0)4.67.14.35.85
_.-~-._.-~-._.-~-._.-~-._.-~-._

**Comment by cyril-r** [comment]
Dans la liste côté aggregator, on vois bien l'aggregation bathy qui est en "completed", mais aucun phénomène associé, alors qu'en dessous on à bien le phénomène de l'aggregation WW3.

![capture](https://cloud.githubusercontent.com/assets/5377420/6177120/2980b602-b304-11e4-8a3c-462178d1ffc7.png)

Et aussi comme tu à pu le noter, dans l'explorer rien n'est retourné pour le phénomène bathy.

**Comment by fretif** [comment]
Peux-tu me montrer le json de l'agrégation "Sirocco bathy" ?

Merci

---- Le jeu., 12 févr. 2015 22:13:49 +0100 cyril-r&lt;notifications@github.com&gt; a écrit ---- 

Dans la liste côté aggregator, on vois bien l'aggregation bathy qui est en "completed", mais aucun phénomène associé, alors qu'en dessous on à bien le phénomène de l'aggregation WW3.

 Et aussi comme tu à pu le noter, dans l'explorer rien n'est retourné pour le phénomène bathy.
 —
Reply to this email directly or view it on GitHub.

_.-~-._.-~-._.-~-._.-~-._.-~-._ 
PhD. Fabien Rétif
Géosciences Montpellier
UMR 5243 - CC 60
Universite Montpellier II
Bat 22 - Bureau 468
Place Eugène Bataillon
34095 Montpellier Cedex 5
France
Tel : +33 (0)4.67.14.35.85
_.-~-._.-~-._.-~-._.-~-._.-~-._

**Comment by cyril-r** [comment]
Si tu demande celui que je lui ai envoyé, il est dans mon premier message, en retour je n'ai qu'un code http 200.

Je vois que tu reste sur client mail pour lire/répondre aux notifs, tu n'a peut-être pas la mise en forme et la coloration sur le site du coup...

Je te remets le json ci-dessous:

``` json
{
    "name": "Sirocco bathy",
    "description": "Bathy from sirocco",
    "phenomena": [
        "bathymetry"
    ],
    "file_url_protocol": "file",
    "file": "sirocco.europe.nc"
}
```

Le fichier existe bien sur le ftp j'ai vérifié.

**Comment by fretif** [comment]
Non non, celui qui te permet de générer la liste des agrégations.

---- Le jeu., 12 févr. 2015 22:21:19 +0100 cyril-r&lt;notifications@github.com&gt; a écrit ---- 

Si tu demande celui que je lui ai envoyé, il est dans mon premier message, en retour je n'ai qu'un code http 200.
 Je vois que tu reste sur client mail pour lire/répondre aux notifs, tu n'a peut-être pas la mise en forme et la coloration sur le site du coup...
 Je te remets le json ci-dessous:
 { "name": "Sirocco bathy", "description": "Bathy from sirocco", "phenomena": [ "bathymetry" ], "file_url_protocol": "file", "file": "sirocco.europe.nc" }
 Le fichier existe bien sur le ftp j'ai vérifié.
 —
Reply to this email directly or view it on GitHub.

_.-~-._.-~-._.-~-._.-~-._.-~-._ 
PhD. Fabien Rétif
Géosciences Montpellier
UMR 5243 - CC 60
Universite Montpellier II
Bat 22 - Bureau 468
Place Eugène Bataillon
34095 Montpellier Cedex 5
France
Tel : +33 (0)4.67.14.35.85
_.-~-._.-~-._.-~-._.-~-._.-~-._

**Comment by cyril-r** [comment]
Ceci? 

```
/aggregations?limit=100&offset=0&status=none&phenomenon=none&sort=desc
```

C'est le filtre par défaut, qui équivaut à "afficher tout, les plus récents en premier, limite d'affichage a 100"

**Comment by fretif** [comment]
Oui, je veux bien le json résultat (ou sinon ton user pour regarder moi même)

---- Le jeu., 12 févr. 2015 22:25:55 +0100 cyril-r&lt;notifications@github.com&gt; a écrit ---- 

Ceci? 
 /aggregations?limit=100&amp;offset=0&amp;status=none&amp;phenomenon=none&amp;sort=desc  C'est le filtre par défaut, qui équivaut à "afficher tout, les plus récents en premier, limite d'affichage a 100"
 —
Reply to this email directly or view it on GitHub.

_.-~-._.-~-._.-~-._.-~-._.-~-._ 
PhD. Fabien Rétif
Géosciences Montpellier
UMR 5243 - CC 60
Universite Montpellier II
Bat 22 - Bureau 468
Place Eugène Bataillon
34095 Montpellier Cedex 5
France
Tel : +33 (0)4.67.14.35.85
_.-~-._.-~-._.-~-._.-~-._.-~-._

**Comment by fretif** [comment]
Si j’exécute cette fonction j'obtiens bien l'aggrégation (en comparant l'heure de création, c'est bien la même) avec le phénomène :

{
        "id": 4,
        "name": "Sirocco bathy",
        "description": "Bathy from sirocco",
        "status": "completed",
        "mode": "YX",
        "creation_date": "2015-02-12 20:40:23",
        "last_updated_date": "2015-02-12 20:40:24",
        "message": "The aggregation has been completed successfully.",
        "pourcent": 100,
        "phenomena": [
            "bathymetry"
        ]
    }

Vérifies le code de ta vue.
Pour info, le champs mode n’apparaît qu'uniquement lorsque l'aggrégation est completed, le reste est tjs renvoyé (désolé pour cet oubli)

Pour l'explorer, le bug vient de moi.

Fabien

---- Le jeu., 12 févr. 2015 22:25:55 +0100 cyril-r&lt;notifications@github.com&gt; a écrit ---- 

Ceci? 
 /aggregations?limit=100&amp;offset=0&amp;status=none&amp;phenomenon=none&amp;sort=desc  C'est le filtre par défaut, qui équivaut à "afficher tout, les plus récents en premier, limite d'affichage a 100"
 —
Reply to this email directly or view it on GitHub.

_.-~-._.-~-._.-~-._.-~-._.-~-._ 
PhD. Fabien Rétif
Géosciences Montpellier
UMR 5243 - CC 60
Universite Montpellier II
Bat 22 - Bureau 468
Place Eugène Bataillon
34095 Montpellier Cedex 5
France
Tel : +33 (0)4.67.14.35.85
_.-~-._.-~-._.-~-._.-~-._.-~-._
