### ISSUE TITLE
Liste des configurations

### ISSUE THREAD

**Issue by cyril-r** [MirmidonDev/mirmidon_unstable#48]
Lorsque je liste les configurations, mais que je n'en ai crée aucune, un comportement anormal se produit.

Lorsque je ne filtre pas (model=none), aucun problème, mais lorsque je filtre sur un des deux modèles supportés, une erreur fatale se produit:

```
array (size=1)
  'errors' => 
    array (size=1)
      0 => 
        array (size=2)
          'message' => string 'Unable to find model 'ww3-wind-current-level'.' (length=46)
          'code' => string '01' (length=2)
```

Romain est passé tout à l'heure et il semblerait que le problème se situe dans 

```
/LOGIC/api/app/controllers/m_configuration_builder/ConfigurationBuilderProcessController.java
```

Au niveau des lignes 118 a 125, en fait quand on à un model=null on ne rentre pas dans la boucle et pas de problème, mais lorsque l'on filtre, c'est à ce niveau que l'erreur se produit.

**Comment by fretif** [comment]
Alors le message est vraiment vrai, le modèle n'existe pas en base.

Les modèles sont instanciés pour la première fois au moment de créer une configuration.

Deux alternatives sont possibles : 
1. faire une fonction qui liste les modèles supportés (et qui les insère au passage). Un peu comme l'aggregator, ce qui te permet de générer la liste à gauche des agrégations possibles (/aggregations/formats)
2. les insérer dans le populator

Fabien

---- Le jeu., 12 févr. 2015 20:12:18 +0100 cyril-r&lt;notifications@github.com&gt; a écrit ---- 

Lorsque je liste les configurations, mais que je n'en ai crée aucune, un comportement anormal se produit.
 Lorsque je ne filtre pas (model=none), aucun problème, mais lorsque je filtre sur un des deux modèles supportés, une erreur fatale se produit:
 array (size=1) 'errors' =&gt; array (size=1) 0 =&gt; array (size=2) 'message' =&gt; string 'Unable to find model 'ww3-wind-current-level'.' (length=46) 'code' =&gt; string '01' (length=2)  Romain est passé tout à l'heure et il semblerait que le problème se situe dans 
 /LOGIC/api/app/controllers/m_configuration_builder/ConfigurationBuilderProcessController.java  Au niveau des lignes 118 a 125, en fait quand on à un model=null on ne rentre pas dans la boucle et pas de problème, mais lorsque l'on filtre, c'est à ce niveau que l'erreur se produit.
 —
Reply to this email directly or view it on GitHub.

_.-~-._.-~-._.-~-._.-~-._.-~-._ 
PhD. Fabien Rétif
Géosciences Montpellier
UMR 5243 - CC 60
Universite Montpellier II
Bat 22 - Bureau 468
Place Eugène Bataillon
34095 Montpellier Cedex 5
France
Tel : +33 (0)4.67.14.35.85
_.-~-._.-~-._.-~-._.-~-._.-~-._

**Comment by cyril-r** [comment]
Ok pas de problème, dans ce cas la la solution n°1 me semble la meilleure, comme ça le jour ou tu ajoute un nouveau modèle, pas besoin d'updater les liens de la GUI, et si tu devais en retirer un pour cause de maintenance il disparaitrait du client aussi.

**Comment by fretif** [comment]
Fixed, j'ai mis l'ajout des modèles dans le populator + une fonction /configurations/models?limit=10&offset=0&sort=asc
