### ISSUE TITLE
/phenomena ne tourne pas tous les phénomènes

### ISSUE THREAD

**Issue by fretif** [MirmidonDev/mirmidon_unstable#49]
La réponse est simple, 

/phenomena?limit=10&offset=0&sort=asc
sort : asc ou desc
La valeur par défaut de limit est 10 si l'on fait /phenomena.
Cyril, je te conseille d'utiliser l'argument limit dans ton appel.

**Comment by cyril-r** [comment]
Ok vu, un petit limit=0 affiche tous les phénomènes.
