### ISSUE TITLE
/configurations/models retourne uniquement les modèles pouvant être créée

### ISSUE THREAD

**Issue by fretif** [MirmidonDev/mirmidon_unstable#51]
J'ai commit un fix qui affiche tous les modèles avec un booléen et les phénomènes manquants pour la création d'une configuration
 {
        "id": 1,
        "key": "s26-ecmwf-mercator",
        "name": "Symphonie S26: ECMWF+MERCATOR",
        "has_enough_data": true
    },
  {
        "id": 2,
        "key": "ww3-wind-level-current",
        "name": "WW3: WIND+CURRENT+LEVEL",
        "missing_data": [
            "wind10m",
            "sea-surface-height",
            "surface-current"
        ],
        "has_enough_data": false
    }

Fabien

**Comment by cyril-r** [comment]
Done.
