### ISSUE TITLE
Pré-routine WW3

### ISSUE THREAD

**Issue by fretif** [MirmidonDev/mirmidon_unstable#52]
Romain, peux-tu vérifier les pré-routines dans WindCurrentLevel.java (strt...)

**Comment by rchailan** [comment]
Ok je regarde dans le we

**Comment by rchailan** [comment]
J'ai mis à jour normalement. @fretif  Fais attention au nom des fichiers mandatory à avoir (les fichiers .inp). Faut qu'on regarde ensemble rapidement comment mettre en place les templates etc. je vois du codage en dur :) 

``` java
[...]
    result.put("start_date", "2013-03-04 12:00:00"); //GMT
    result.put("end_date", "2013-03-06 12:00:00"); //GMT
[...]

```

**Comment by fretif** [comment]
Lool, Cyril et toi n'arrêtaient pas de me dire, il y a du code en dur =&gt; voir Julien , nah !

OK pour les fichiers inp.

---- Le ven., 13 févr. 2015 17:33:13 +0100 Romain Chailan&lt;notifications@github.com&gt; a écrit ---- 

J'ai mis à jour normalement. @fretif Fais attention au nom des fichiers mandatory à avoir (les fichiers .inp). Faut qu'on regarde ensemble rapidement comment mettre en place les templates etc. je vois du codage en dur :) 
 [...] result.put("start_date", "2013-03-04 12:00:00"); //GMT result.put("end_date", "2013-03-06 12:00:00"); //GMT [...] 
 —
Reply to this email directly or view it on GitHub.

_.-~-._.-~-._.-~-._.-~-._.-~-._ 
PhD. Fabien Rétif
Géosciences Montpellier
UMR 5243 - CC 60
Universite Montpellier II
Bat 22 - Bureau 468
Place Eugène Bataillon
34095 Montpellier Cedex 5
France
Tel : +33 (0)4.67.14.35.85
_.-~-._.-~-._.-~-._.-~-._.-~-._
