### ISSUE TITLE
Impossible de créer une aggregation

### ISSUE THREAD

**Issue by cyril-r** [MirmidonDev/mirmidon_unstable#55]
@jhuon viens de me faire remarquer qu'il n'était plus possible de créer d'aggregations.

Exemple pour ecmwf:

Play:

```
2015-02-19 14:34:52,272 - [DEBUG] - from application in play-akka.actor.default-dispatcher-21 
[aggregator] *Import data from ECMWF format* Executes the process with

2015-02-19 14:34:52,272 - [DEBUG] - from application in play-akka.actor.default-dispatcher-21 
[aggregator] *Import data from ECMWF format*Inputs :{dim=3, files=http://p4x-650.gateworld.fr:9082/explorer/media?token=8c9e3dec-5346-49db-9346-2af57eeebe46, phenomena=wind10m atmospheric-land-sea-mask surface-pressure surface-sensible-heat-flux surface-latent-heat-flux air-temperature2m dewpoint-temperature2m surface-solar-radiation-downwards surface-thermal-radiation-downwards surface-solar-radiation surface-thermal-radiation total-rain, description=test, name=test, files_url_protocol=file}

2015-02-19 14:34:52,272 - [DEBUG] - from application in play-akka.actor.default-dispatcher-21 
[aggregator] *Import data from ECMWF format*Ouputs :{}

```

Constellation:

```
http://localhost:8092/constellation/WS/wps/symphonie-builder?VERSION=1.0.0&SERVICE=WPS&IDENTIFIER=urn%3Aogc%3Acstl%3Awps%3Aaggregator%3Aimport-netcdf-ecmwf&REQUEST=DescribeProcess
http://localhost:8092/constellation/WS/wps/symphonie-builder?VERSION=1.0.0&SERVICE=WPS&IDENTIFIER=urn%3Aogc%3Acstl%3Awps%3Asymphonie-builder%3As26-ecmwf-mercator&REQUEST=DescribeProcess

```

**Comment by fretif** [comment]
Si il y a une gestion des exceptions, il serait bien de s'en servir ! Je pari que l'api vous retourne une erreur ????

**Comment by jhuon** [comment]
An API error occured!
Error 1/1
Code: 02
Message: Unable to create a WPS monitor for the aggregation 'ECMWF 1'.

**Comment by cyril-r** [comment]
```
    An API error occured!
    Error 1/1
    Code: 02
    Message: Unable to create a WPS monitor for the aggregation 'test'.
```

**Comment by fretif** [comment]
Merci !!!!!!!!!!!!!!!!!!

**Comment by cyril-r** [comment]
Synchro :-)

**Comment by fretif** [comment]
Je viens de pousser un fix, il faut re-déployer. Attention à bien vérifier que la lib OCG Client est à jour à la suite du re-déployement.

**Comment by cyril-r** [comment]
Ok je veux bien redéployer, mais un petit hint pour être sur que la fameuse lib "ocg" est à jour (je vérifie comment?)

**Comment by fretif** [comment]
La date de compilation du jar par exemple.

---- Le jeu., 19 févr. 2015 16:55:26 +0100 cyril-r&lt;notifications@github.com&gt; a écrit ---- 

Ok je veux bien redéployer, mais un petit hint pour être sur que la fameuse lib "ocg" est à jour (je vérifie comment?)
 —
Reply to this email directly or view it on GitHub.

_.-~-._.-~-._.-~-._.-~-._.-~-._ 
PhD. Fabien Rétif
Géosciences Montpellier
UMR 5243 - CC 60
Universite Montpellier II
Bat 22 - Bureau 468
Place Eugène Bataillon
34095 Montpellier Cedex 5
France
Tel : +33 (0)4.67.14.35.85
_.-~-._.-~-._.-~-._.-~-._.-~-._

**Comment by cyril-r** [comment]
Ok

Le 19 février 2015 17:02:44 GMT+01:00, "Fabien Rétif" notifications@github.com a écrit :

> La date de compilation du jar par exemple.
> 
> ---- Le jeu., 19 févr. 2015 16:55:26 +0100
> cyril-r&lt;notifications@github.com&gt; a écrit ---- 
> 
> Ok je veux bien redéployer, mais un petit hint pour être sur que la
> fameuse lib "ocg" est à jour (je vérifie comment?)
> —
> Reply to this email directly or view it on GitHub.
> 
> _.-~-._.-~-._.-~-._.-~-._.-~-._ 
> PhD. Fabien Rétif
> Géosciences Montpellier
> UMR 5243 - CC 60
> Universite Montpellier II
> Bat 22 - Bureau 468
> Place Eugène Bataillon
> 34095 Montpellier Cedex 5
> France
> Tel : +33 (0)4.67.14.35.85
> _.-~-._.-~-._.-~-._.-~-._.-~-._ 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/MirmidonDev/mirmidon_unstable/issues/55#issuecomment-75078005

## 

Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by cyril-r** [comment]
Ca semble fonctionner maintenant, par contre j'ai vu des warnings quand j'ai crée une config symphonie (mais elle est visiblement passée).

Tu veux un log plus complet ou c'est normal?
