### ISSUE TITLE
Config builder : camelCase in configuration list

### ISSUE THREAD

**Issue by cyril-r** [MirmidonDev/mirmidon_unstable#56]
Lorsque je liste les configurations (GET /configurations), le JSON renvoyé par l'API est correct mais les clés sont au format camelCase au lieu de snake_case.

exemple de retour :

```
array (size=2)
  0 => 
    array (size=9)
      'id' => int 2
      'name' => string 'Test S26 n2' (length=11)
      'totaltasks' => int 1
      'nodes' => int 1
      'taskpernode' => int 1
      'creationDate' => string '2015-02-19 13:29:38' (length=19)
      'fieldsite' => string 'megapol' (length=7)
      'isAggregate' => boolean false
      'previewImageFiles' => 
        array (size=0)
          empty
```

**Comment by fretif** [comment]
J'ai poussé un début de fix mais il faudra voir avec Romain car je json risque de changer avec le preview.

---- Le jeu., 19 févr. 2015 14:40:21 +0100 cyril-r&lt;notifications@github.com&gt; a écrit ---- 

Lorsque je liste les configurations (GET /configurations), le JSON renvoyé par l'API est correct mais les clés sont au format camelCase au lieu de snake_case.
 exemple de retour :
 array (size=2) 0 =&gt; array (size=9) 'id' =&gt; int 2 'name' =&gt; string 'Test S26 n2' (length=11) 'totaltasks' =&gt; int 1 'nodes' =&gt; int 1 'taskpernode' =&gt; int 1 'creationDate' =&gt; string '2015-02-19 13:29:38' (length=19) 'fieldsite' =&gt; string 'megapol' (length=7) 'isAggregate' =&gt; boolean false 'previewImageFiles' =&gt; array (size=0) empty  —
Reply to this email directly or view it on GitHub.

_.-~-._.-~-._.-~-._.-~-._.-~-._ 
PhD. Fabien Rétif
Géosciences Montpellier
UMR 5243 - CC 60
Universite Montpellier II
Bat 22 - Bureau 468
Place Eugène Bataillon
34095 Montpellier Cedex 5
France
Tel : +33 (0)4.67.14.35.85
_.-~-._.-~-._.-~-._.-~-._.-~-._

**Comment by cyril-r** [comment]
je close le ticket, pour le moment c'est ok on verra plus tard s'il y a modifs.
