### ISSUE TITLE
API ne démarre plus

### ISSUE THREAD

**Issue by cyril-r** [MirmidonDev/mirmidon_unstable#57]
J'ai fait un redéploy, deux fois pour être sur en cleanant complètement la DB, l'API refuse de démarrer maintenant.

Constellation est OK et démarre, mais play plante.

Log play:

```
[info] Set current project to Mirmidon-Logic (in build file:/data/MIRMIDON/unstable/mirmidon/LOGIC/api/)
[info] Compiling 4 Scala sources and 84 Java sources to /data/MIRMIDON/unstable/mirmidon/LOGIC/api/target/scala-2.10/classes...
[error] warning: Supported source version 'RELEASE_6' from annotation processor 'org.antlr.v4.runtime.misc.NullUsageProcessor' less than -source '1.7'
[error] /data/MIRMIDON/unstable/mirmidon/LOGIC/api/app/controllers/m_integrator/DatabasePopulator.java:212: error: unreported exception CapabilitiesException; must be caught or declared to be thrown
[error]                 ProcessController controller = new ImportFromNetcdfECMWF();
[error]                                                ^
[error] /data/MIRMIDON/unstable/mirmidon/LOGIC/api/app/controllers/m_integrator/DatabasePopulator.java:223: error: unreported exception CapabilitiesException; must be caught or declared to be thrown
[error]                 ProcessController controller = new ImportFromNetcdfSymphonie();
[error]                                                ^
[error] /data/MIRMIDON/unstable/mirmidon/LOGIC/api/app/controllers/m_integrator/DatabasePopulator.java:234: error: unreported exception CapabilitiesException; must be caught or declared to be thrown
[error]                 ProcessController controller = new ImportFromNetcdfWW3();
[error]                                                ^
[error] /data/MIRMIDON/unstable/mirmidon/LOGIC/api/app/controllers/m_integrator/DatabasePopulator.java:248: error: unreported exception CapabilitiesException; must be caught or declared to be thrown
[error]             ProcessController controller = new S26EcmwfMercator();
[error]                                            ^
[error] /data/MIRMIDON/unstable/mirmidon/LOGIC/api/app/controllers/m_integrator/DatabasePopulator.java:258: error: unreported exception CapabilitiesException; must be caught or declared to be thrown
[error]             ProcessController controller = new WindLevelCurrent();
[error]                                            ^
[error] Note: Some input files use or override a deprecated API.
[error] Note: Recompile with -Xlint:deprecation for details.
[error] Note: Some input files use unchecked or unsafe operations.
[error] Note: Recompile with -Xlint:unchecked for details.
[error] 5 errors
[error] 1 warning
[error] (compile:compile) javac returned nonzero exit code

Cannot start with errors.
```

**Comment by fretif** [comment]
ah oui, je n'ai pas poussé mon populator parce qu'il est configurer pour ma machine mais il y a besoin de modifs.
Je propose de pousser avec mes valeurs et tu re-édites avec la config du serveur ? 

La config, c'est ce genre de truc
key = "configbaseDirectory";
        myEntry = ConfigurationEntry.find.where().eq("key",key).findUnique();  
        if (myEntry == null) {  
            final ConfigurationEntry wps = new ConfigurationEntry(key, "/work/littocms/db/configs/");
        }

---- Le jeu., 19 févr. 2015 17:58:20 +0100 cyril-r&lt;notifications@github.com&gt; a écrit ---- 

J'ai fait un redéploy, deux fois pour être sur en cleanant complètement la DB, l'API refuse de démarrer maintenant.
 Constellation est OK et démarre, mais play plante.
 Log play:
 [info] Set current project to Mirmidon-Logic (in build file:/data/MIRMIDON/unstable/mirmidon/LOGIC/api/) [info] Compiling 4 Scala sources and 84 Java sources to /data/MIRMIDON/unstable/mirmidon/LOGIC/api/target/scala-2.10/classes... [error] warning: Supported source version 'RELEASE_6' from annotation processor 'org.antlr.v4.runtime.misc.NullUsageProcessor' less than -source '1.7' [error] /data/MIRMIDON/unstable/mirmidon/LOGIC/api/app/controllers/m_integrator/DatabasePopulator.java:212: error: unreported exception CapabilitiesException; must be caught or declared to be thrown [error] ProcessController controller = new ImportFromNetcdfECMWF(); [error] ^ [error] /data/MIRMIDON/unstable/mirmidon/LOGIC/api/app/controllers/m_integrator/DatabasePopulator.java:223: error: unreported exception CapabilitiesException; must be caught or declared to be thrown [error] ProcessController controller = new ImportFromNetcdfSymphonie(); [error] ^ [error] /data/MIRMIDON/unstable/mirmidon/LOGIC/api/app/controllers/m_integrator/DatabasePopulator.java:234: error: unreported exception CapabilitiesException; must be caught or declared to be thrown [error] ProcessController controller = new ImportFromNetcdfWW3(); [error] ^ [error] /data/MIRMIDON/unstable/mirmidon/LOGIC/api/app/controllers/m_integrator/DatabasePopulator.java:248: error: unreported exception CapabilitiesException; must be caught or declared to be thrown [error] ProcessController controller = new S26EcmwfMercator(); [error] ^ [error] /data/MIRMIDON/unstable/mirmidon/LOGIC/api/app/controllers/m_integrator/DatabasePopulator.java:258: error: unreported exception CapabilitiesException; must be caught or declared to be thrown [error] ProcessController controller = new WindLevelCurrent(); [error] ^ [error] Note: Some input files use or override a deprecated API. [error] Note: Recompile with -Xlint:deprecation for details. [error] Note: Some input files use unchecked or unsafe operations. [error] Note: Recompile with -Xlint:unchecked for details. [error] 5 errors [error] 1 warning [error](compile:compile) javac returned nonzero exit code Cannot start with errors.  —
Reply to this email directly or view it on GitHub.

_.-~-._.-~-._.-~-._.-~-._.-~-._ 
PhD. Fabien Rétif
Géosciences Montpellier
UMR 5243 - CC 60
Universite Montpellier II
Bat 22 - Bureau 468
Place Eugène Bataillon
34095 Montpellier Cedex 5
France
Tel : +33 (0)4.67.14.35.85
_.-~-._.-~-._.-~-._.-~-._.-~-._

**Comment by cyril-r** [comment]
Bon je vais devoir le faire a la main alors après le redéploiement de l'archive de travail et juste avant le lancement initial de play!.

Pour ton code, de quel fichier s'agit-il ?
Je vois /work/littocms/db/configs, est-ce que tu sait ou ça doit pointer sur le microserveur? j'ai cherché mais je n'ai pas trouvé la suite de répertoires ".../db/configs" dans mirmidon.

N'oublie pas une fois que tout sera bon de me prévenir quand ce fix a la main ne sera plus nécessaire.

**Comment by fretif** [comment]
non laisse tomber, je m'en occupe. Je te préviens quand j'ai commit le fix

---- Le jeu., 19 févr. 2015 18:21:33 +0100 cyril-r&lt;notifications@github.com&gt; a écrit ---- 

Bon je vais devoir le faire a la main alors après le redéploiement de l'archive de travail et juste avant le lancement initial de play!.
 Pour ton code, de quel fichier s'agit-il ?
 Je vois /work/littocms/db/configs, est-ce que tu sait ou ça doit pointer sur le microserveur? j'ai cherché mais je n'ai pas trouvé la suite de répertoires ".../db/configs" dans mirmidon.
 N'oublie pas une fois que tout sera bon de me prévenir quand ce fix a la main ne sera plus nécessaire.
 —
Reply to this email directly or view it on GitHub.

_.-~-._.-~-._.-~-._.-~-._.-~-._ 
PhD. Fabien Rétif
Géosciences Montpellier
UMR 5243 - CC 60
Universite Montpellier II
Bat 22 - Bureau 468
Place Eugène Bataillon
34095 Montpellier Cedex 5
France
Tel : +33 (0)4.67.14.35.85
_.-~-._.-~-._.-~-._.-~-._.-~-._

**Comment by cyril-r** [comment]
Ok, sorry ce n'est pas que je ne veux pas le faire, mais je n'avais vraiment pas assez de détails dans ton post pour intervenir sur le serveur, ça aurait été sur GUI j'aurais de suite su ou ce code allait mais la :-)

**Comment by fretif** [comment]
done !

---- Le jeu., 19 févr. 2015 18:33:53 +0100 cyril-r&lt;notifications@github.com&gt; a écrit ---- 

Ok, sorry ce n'est pas que je ne veux pas le faire, mais je n'avais vraiment pas assez de détails dans ton post pour intervenir sur le serveur, ça aurait été sur GUI j'aurais de suite su ou ce code allait mais la :-)
 —
Reply to this email directly or view it on GitHub.

_.-~-._.-~-._.-~-._.-~-._.-~-._ 
PhD. Fabien Rétif
Géosciences Montpellier
UMR 5243 - CC 60
Universite Montpellier II
Bat 22 - Bureau 468
Place Eugène Bataillon
34095 Montpellier Cedex 5
France
Tel : +33 (0)4.67.14.35.85
_.-~-._.-~-._.-~-._.-~-._.-~-._

**Comment by cyril-r** [comment]
redéploiement ok.
