### ISSUE TITLE
Rename /toto to /session_check or something meaningful

### ISSUE THREAD

**Issue by cyril-r** [MirmidonDev/mirmidon_unstable#60]
J'ai réalisé une fonction de détection de fermeture de session sur la GUI et je me base sur la route /toto pour vérifier que ma session est fermée, et que ce n'est pas l'accès à la ressource demandée qui m'est refusée.

Au final vu que cette méthode de session check côté API est utilisée par la GUI et donc importante, il faudrait changer la route pour quelque chose de plus significatif.

**Comment by rchailan** [comment]
Ok. GET /authorized ?

**Comment by cyril-r** [comment]
peu importe tant que ce n'est pas /toto :-)

**Comment by rchailan** [comment]
done. Ca marchera au prochain redeploy. J'ai bien mis GET /authorized pour la route.
