### ISSUE TITLE
Image Preview already exists

### ISSUE THREAD

**Issue by jhuon** [MirmidonDev/mirmidon_unstable#68]
When previewing image, error occured: 
The configuration seems to already have 1 preview files. Abort. (2)

**Comment by fretif** [comment]
Romain appelle la génération de preview automatiquement à la fin d'une commande.
Mais comme elle est asyncrhone, elle mets du temps à se faire et c'est pourquoi ton bouton s'affiche quand même. Cela devrait être régler avec le booléen hasPreviews....
