### ISSUE TITLE
 /commands/latest

### ISSUE THREAD

**Issue by rchailan** [MirmidonDev/mirmidon_unstable#8]
Issue when acceding to the resource : 

Execution exception
[RuntimeException: get id on [models.m_core_user.MUser] type[java.lang.Long] threw error.]
In /data/MIRMIDON/unstable/mirmidon/LOGIC/app/controllers/m_command_scheduler/CommandManager.java at line 176.
173  
174        ObjectNode container = Json.newObject();
175        ObjectNode commandListJson = Json.newObject();
176        List<MCommand> commandList = MCommand.find.where().eq("user",user.getId()).isNotNull("endDate").order().desc("endDate").setMaxRows(5).findList();
177  
178        for (final MCommand command : commandList) {
179         commandListJson.put(String.valueOf(command.getId()),command.toJson());
180        }
181        return ok(commandListJson);

**Comment by rchailan** [comment]
Fixé avec commit 4123c63

**Comment by cyril-r** [comment]
Not working.

GET @ http://...:9082/configurations/latest
Execution exception
[NullPointerException: null]
In /data/MIRMIDON/unstable/mirmidon/LOGIC/app/controllers/m_configuration_builder/ConfigurationManager.java at line 155.
152     MUser user = MUser.find.where().eq("token", token).findUnique();
153  
154     ObjectNode configurationsList = Json.newObject();
155        List<MConfiguration> MConfigurationList = MConfiguration.find.where().eq("muser",user.getId()).order().desc("creationDate").setMaxRows(5).findList();
156        for (final MConfiguration configuration : MConfigurationList) {
157         configurationsList.put(String.valueOf(configuration.getId()),
158                configuration.toJson());
159        }
160        return ok(configurationsList);

**Comment by rchailan** [comment]
Should be fixed by now
